["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
storage = [
    "homework_6/contracts/storage/storage.cairo",
]
storage_ownable = [
    "homework_7/contracts/storage/storage.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./cairo_contracts/src"]
