["protostar.config"]
protostar_version = "0.7.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
storage = [
    "homework_6/contracts/storage/storage.cairo",
]
storage_ownable = [
    "homework_7/contracts/storage/storage.cairo",
]
erc20 = [
    "homework_8/contracts/erc20/erc20.cairo",
]
erc721 = [
    "homework_9/contracts/erc721/erc721.cairo",
]
consortium = [
    "homework_12/contracts/consortium/consortium.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./cairo_contracts/src"]
